import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';globalThis.crypto??=webcrypto;
import {parseBallot,generateKeys,assertRsaPair,encryptVote,decryptVote,validName,publish,history,messageBase,keyFingerprint,sign,verify,validateEndpoints,assignedEndpoint,saveEndpointsCache,loadEndpointsCache,saveSheetCache,loadSheetCache,fetchWithTimeout} from '../shared/common.js';
const uuid='12345678-1234-4123-8123-123456789abc',endpoint='https://script.google.com/macros/s/deployment_identifier_123/exec';
const csv=[
 ',chave pública,,,,,,' ,
 ',x,,,,Maria Silva-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA,,',
 ',"1 = servidor rodando, e 0 = parado/pausado",1,,,,,',
 '', '',
 ',DIACONOS SEDE,quantidade de respostas aceitas,embaralhar,exibir imagens,,,',
 'https://img.test/joao.jpg,João,2,1,,,,',
 'https://img.test/jose.jpg,José,mostrar imagens,,,,,',
 'https://img.test/lucas.jpg,Lucas,1,,,,,',
 'https://img.test/marcos.jpg,Marcos,,,,,,',
 '',
 ',DIÁCONOS LAGE,quantidade de respostas aceitas,embaralhar,exibir imagens,,,',
 ',Ana,1,0,0,,,',',Bia,,,,,,',
 ',,,,,,,https://script.google.com/macros/s/deployment_identifier_123/exec'
].join('\n');
test('parser aplica colunas transpostas, imagens e novo booleano',async()=>{const b=await parseBallot(csv);assert.equal(b.state,'1');assert.deepEqual(b.questions.map(q=>[q.count,q.shuffle,q.showImages,q.options.length]),[[2,true,true,4],[1,false,false,2]]);assert.equal(b.questions[0].options[0].image,'https://img.test/joao.jpg');assert.equal(b.validated.length,1);assert.deepEqual(b.endpoints,[endpoint]);});
test('fingerprint da cédula é determinística',async()=>assert.equal((await parseBallot(csv)).ballotFingerprint,(await parseBallot(csv)).ballotFingerprint));
test('imagem em célula pode estar ausente no CSV do Google',async()=>assert.equal((await parseBallot(csv.replace('https://img.test/jose.jpg',''))).questions[0].showImages,true));
test('nome exige duas palavras e aceita diacríticos',()=>{assert.equal(validName(' João D’Ávila-Silva '),'João D’Ávila-Silva');assert.throws(()=>validName('João1 Silva'));});
test('voto híbrido cifra e decifra',async()=>{const k=await generateKeys();await assertRsaPair(k.publicKey,k.privateKey);const plain={secret:'não aparece'},env=await encryptVote(plain,k.publicKey);assert.equal(JSON.stringify(env).includes('secret'),false);assert.deepEqual(await decryptVote(env,k.privateKey),plain);});
test('endpoints exigem Web App normalizado, sem duplicatas',()=>{assert.deepEqual(validateEndpoints([endpoint+'/']),[endpoint]);assert.throws(()=>validateEndpoints([endpoint,endpoint+'/']));assert.throws(()=>validateEndpoints(['https://example.com/x']));});
test('atribuição de endpoint é determinística',async()=>assert.deepEqual(await assignedEndpoint(uuid,'device', [endpoint]),await assignedEndpoint(uuid,'device',[endpoint])));
test('cache de endpoints é vinculado à planilha e protegido por fingerprint',async()=>{const values=new Map(),cache={get:k=>values.get(k)??null,set:(k,v)=>values.set(k,v),json(k){try{return JSON.parse(this.get(k));}catch{return null;}},put(k,v){this.set(k,JSON.stringify(v));}};const saved=await saveEndpointsCache(cache,'sheet_identifier_1234567890',[endpoint+'/']);assert.deepEqual(saved.endpoints,[endpoint]);assert.deepEqual(await loadEndpointsCache(cache,'sheet_identifier_1234567890'),saved);assert.equal(await loadEndpointsCache(cache,'another_sheet_identifier_1'),null);values.set('endpointsCache',JSON.stringify({...saved,fingerprint:'invalid'}));assert.equal(await loadEndpointsCache(cache,'sheet_identifier_1234567890'),null);});
test('cache da planilha expira e verifica integridade',async()=>{const values=new Map(),cache={get:k=>values.get(k)??null,set:(k,v)=>values.set(k,v),json(k){try{return JSON.parse(this.get(k));}catch{return null;}},put(k,v){this.set(k,JSON.stringify(v));}},ballot=await parseBallot(csv);await saveSheetCache(cache,'sheet_identifier_1234567890',ballot,1000);assert.deepEqual(await loadSheetCache(cache,'sheet_identifier_1234567890',{now:15999}),ballot);assert.equal(await loadSheetCache(cache,'sheet_identifier_1234567890',{now:16001}),null);const changed=JSON.parse(values.get('sheetCache'));changed.ballot.state='0';values.set('sheetCache',JSON.stringify(changed));assert.equal(await loadSheetCache(cache,'sheet_identifier_1234567890',{now:1500}),null);});
test('requisição pendurada é cancelada com mensagem clara',async()=>{const original=globalThis.fetch;globalThis.fetch=(_url,{signal})=>new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('aborted'),{name:'AbortError'}))));try{await assert.rejects(fetchWithTimeout('https://example.test',{},5),/demorou demais/);}finally{globalThis.fetch=original;}});
test('publicação usa append text/plain e valida recibo lógico',async()=>{const original=globalThis.fetch;let request;globalThis.fetch=async(url,options)=>(request={url,options},{ok:true,json:async()=>({ok:true,sessionId:uuid,cursor:4,hash:'abc'})});try{await publish(uuid,{type:'VOTE'},endpoint);}finally{globalThis.fetch=original;}assert.equal(request.url,endpoint);assert.equal(request.options.headers['Content-Type'],'text/plain;charset=UTF-8');assert.equal(JSON.parse(request.options.body).action,'append');});
test('histórico valida cursor e hash sem contaminar assinatura',async()=>{const original=globalThis.fetch,keys=await generateKeys(),fingerprint=await keyFingerprint(keys.adminSigningPublicKey),message={...messageBase('PUBLIC_KEY',uuid,fingerprint),adminSigningPublicKeyJwk:keys.adminSigningPublicKey};await sign(message,keys.adminSigningPrivateKey);const json=JSON.stringify(message),hash=Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(json))).toString('base64url');globalThis.fetch=async()=>({ok:true,json:async()=>({ok:true,sessionId:uuid,hasMore:false,nextAfter:1,records:[{cursor:1,type:'PUBLIC_KEY',json,hash,receivedAt:'now'}]})});let restored;try{[restored]=await history(uuid,endpoint);}finally{globalThis.fetch=original;}assert.equal(restored._endpoint,endpoint);assert.equal(Object.keys(restored).includes('_endpoint'),false);assert.equal(await verify(restored,keys.adminSigningPublicKey),true);});
