const MAX_BODY_BYTES=100000,MAX_PAGE_SIZE=500,TYPES=new Set(['PUBLIC_KEY','NAME_REQUEST','VOTE']),HEADER=['cursor','type','id','receivedAt','json','sha256'];
function configurar(){const s=SpreadsheetApp.getActiveSpreadsheet();if(!s)throw new Error('Vincule este script a uma planilha.');PropertiesService.getScriptProperties().setProperty('SPREADSHEET_ID',s.getId());}
function doGet(e){return responder_(function(){const p=e&&e.parameter||{};if(p.action==='health')return {ok:true,service:'election-channel',spreadsheetId:planilha_().getId()};if(p.action!=='messages')throw erro_(400,'Ação inválida.');const sessionId=uuid_(p.sessionId),after=inteiro_(p.after||'0',0,Number.MAX_SAFE_INTEGER,'after'),limit=inteiro_(p.limit||String(MAX_PAGE_SIZE),1,MAX_PAGE_SIZE,'limit'),sheet=planilha_().getSheetByName(sessionId);if(!sheet)return {ok:true,sessionId,records:[],hasMore:false,nextAfter:after};validarCabecalho_(sheet);const records=[],last=sheet.getLastRow();if(last>1){const rows=sheet.getRange(2,1,last-1,HEADER.length).getDisplayValues();for(const r of rows){const cursor=Number(r[0]);if(cursor<=after)continue;records.push({cursor,type:r[1],id:r[2],receivedAt:r[3],json:r[4],hash:r[5]});if(records.length===limit+1)break;}}const hasMore=records.length>limit;if(hasMore)records.pop();return {ok:true,sessionId,records,hasMore,nextAfter:records.length?records[records.length-1].cursor:after};});}
function doPost(e){return responder_(function(){const raw=String(e&&e.postData&&e.postData.contents||'');if(!raw)throw erro_(400,'Corpo ausente.');if(Utilities.newBlob(raw).getBytes().length>MAX_BODY_BYTES)throw erro_(413,'Corpo excessivo.');let input;try{input=JSON.parse(raw);}catch(_){throw erro_(400,'JSON inválido.');}if(input.action!=='append'||!input.message||typeof input.message!=='object')throw erro_(400,'Publicação inválida.');const sessionId=uuid_(input.sessionId),m=input.message;if(m.sessionId!==sessionId||m.protocolVersion!==1||!TYPES.has(m.type))throw erro_(400,'Sessão, versão ou tipo inválido.');const id=idempotencia_(m),json=JSON.stringify(m),hash=sha256_(json),lock=LockService.getScriptLock();if(!lock.tryLock(25000))throw erro_(503,'Canal ocupado.');try{const sheet=guiaDaSessao_(sessionId),last=sheet.getLastRow();if(last>1){for(const r of sheet.getRange(2,1,last-1,HEADER.length).getDisplayValues()){if(r[2]!==id)continue;if(r[4]!==json||r[5]!==hash)throw erro_(409,'Identificador idempotente conflitante.');return {ok:true,duplicate:true,sessionId,cursor:Number(r[0]),id,hash,receivedAt:r[3]};}}const cursor=last===1?1:Number(sheet.getRange(last,1).getValue())+1;if(!Number.isSafeInteger(cursor)||cursor<1)throw erro_(500,'Cursor inválido.');const receivedAt=new Date().toISOString();sheet.getRange(last+1,1,1,HEADER.length).setNumberFormat('@').setValues([[String(cursor),m.type,id,receivedAt,json,hash]]);SpreadsheetApp.flush();return {ok:true,duplicate:false,sessionId,cursor,id,hash,receivedAt};}finally{lock.releaseLock();}});}
function guiaDaSessao_(id){const ss=planilha_();let s=ss.getSheetByName(id);if(!s){s=ss.insertSheet(id);s.getRange(1,1,1,HEADER.length).setValues([HEADER]);s.setFrozenRows(1);}validarCabecalho_(s);return s;}
function validarCabecalho_(s){const a=s.getRange(1,1,1,HEADER.length).getDisplayValues()[0];if(!HEADER.every(function(v,i){return a[i]===v;}))throw erro_(409,'Guia da sessão possui cabeçalho incompatível.');}
function planilha_(){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');if(!id)throw erro_(500,'Execute configurar() antes de publicar.');return SpreadsheetApp.openById(id);}
function idempotencia_(m){let id='';if(m.type==='PUBLIC_KEY')id=String(m.signingKeyFingerprint||'')+':PUBLIC_KEY';else if(m.type==='NAME_REQUEST')id=String(m.requestId||'');else if(m.type==='VOTE')id=String(m.ballotId||'');if(!id||id.length>300)throw erro_(400,'Identificador idempotente ausente.');return id;}
function uuid_(v){const s=String(v||'').toLowerCase();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(s))throw erro_(400,'UUID inválido.');return s;}
function inteiro_(v,min,max,n){if(!/^(0|[1-9][0-9]*)$/.test(String(v)))throw erro_(400,n+' inválido.');const x=Number(v);if(!Number.isSafeInteger(x)||x<min||x>max)throw erro_(400,n+' inválido.');return x;}
function sha256_(s){return Utilities.base64EncodeWebSafe(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,s,Utilities.Charset.UTF_8)).replace(/=+$/,'');}
function erro_(status,message){const e=new Error(message);e.status=status;return e;}
function responder_(fn){let result;try{result=fn();}catch(e){result={ok:false,status:e.status||500,error:e.message||'Erro interno.'};}return ContentService.createTextOutput(JSON.stringify(result)).setMimeType(ContentService.MimeType.JSON);}
