const V=2,MAX_BODY=100000,CLOCK=300000,MAX=2000;
const TABLES={sessions:['sessionId','capHash','signJwk','signFp','rsaPem','rsaFp','endpointsFp','state','createdAt'],names:['sessionId','deviceId','name','deviceJwk','status','requestId','updatedAt'],votes:['sessionId','deviceId','ballotId','rsaFp','json','receivedAt'],audit:['sessionId','at','action','requestId','authorFp','result'],nonces:['sessionId','hash','expiresAt'],panels:['sessionId','capHash','expiresAt','revokedAt']};
function configurar(){const s=SpreadsheetApp.getActiveSpreadsheet();if(!s)throw Error('Vincule o script a uma planilha.');PropertiesService.getScriptProperties().setProperty('SPREADSHEET_ID',s.getId());Object.keys(TABLES).forEach(n=>tab_(n,true));}
function doGet(e){return reply_(()=>{if(e&&e.parameter&&e.parameter.action==='health')return {ok:true,service:'election-channel',protocolVersion:V};throw err_(404,'Operação indisponível.');});}
function doPost(e){return reply_(()=>{const raw=String(e&&e.postData&&e.postData.contents||'');if(!raw||Utilities.newBlob(raw).getBytes().length>MAX_BODY)throw err_(400,'Corpo inválido.');let x;try{x=JSON.parse(raw);}catch(_){throw err_(400,'JSON inválido.');}if(x.protocolVersion!==V)throw err_(409,'Versão incompatível.');const pub={publicConfig:config_,authorizationStatus:authStatus_,messageReceipt:receipt_,appendNameRequest:name_,appendVote:vote_,panelSnapshot:panel_};const adm={listNameRequests:listNames_,approveDevice:x=>decision_(x,'approved'),rejectDevice:x=>decision_(x,'rejected'),revokeDevice:x=>decision_(x,'revoked'),listEncryptedVotes:listVotes_,sessionStatus:status_,issuePanelCapability:issuePanel_,revokePanelCapability:revokePanel_};if(pub[x.action])return pub[x.action](x);if(x.action==='registerSession')return register_(x);if(adm[x.action])return admin_(x,adm[x.action]);throw err_(400,'Ação inválida.');});}
function register_(x){fresh_(x);const id=uuid_(x.sessionId);cap_(x.adminCapability);fp_(x.adminSigningKeyFingerprint);fp_(x.encryptionKeyFingerprint);fp_(x.endpointListFingerprint);if(!x.adminSigningPublicKeyJwk||x.adminSigningPublicKeyJwk.kty!=='EC'||x.adminSigningPublicKeyJwk.crv!=='P-256'||sha_(canon_(x.adminSigningPublicKeyJwk))!==x.adminSigningKeyFingerprint||sha_(pem_(x.encryptionPublicKeyPem))!==x.encryptionKeyFingerprint||!verify_(x,x.adminSigningPublicKeyJwk))throw err_(403,'Autorização inválida.');return lock_(()=>{const old=rows_('sessions').find(r=>r[0]===id),row=[id,sha_(x.adminCapability),JSON.stringify(x.adminSigningPublicKeyJwk),x.adminSigningKeyFingerprint,x.encryptionPublicKeyPem,x.encryptionKeyFingerprint,x.endpointListFingerprint,'active',new Date().toISOString()];if(old){if(old.slice(1,7).join('\n')!==row.slice(1,7).join('\n'))throw err_(409,'Registro conflitante.');return {ok:true,duplicate:true,sessionId:id};}add_('sessions',row);audit_(id,x,'accepted');return {ok:true,duplicate:false,sessionId:id};});}
function admin_(x,fn){fresh_(x);const s=session_(uuid_(x.sessionId));if(!s||!same_(sha_(String(x.adminCapability||'')),s.capHash)||!verify_(x,s.jwk))throw err_(403,'Autorização inválida.');return lock_(()=>{nonce_(s.id,x.nonce);try{const out=fn(x,s);audit_(s.id,x,'accepted');return out;}catch(e){audit_(s.id,x,'rejected');throw e;}});}
function config_(x){const s=session_(uuid_(x.sessionId));if(!s)throw err_(404,'Sessão indisponível.');return {ok:true,sessionId:s.id,protocolVersion:V,adminSigningPublicKeyJwk:s.jwk,adminSigningKeyFingerprint:s.signFp,encryptionPublicKeyPem:s.rsaPem,encryptionKeyFingerprint:s.rsaFp,endpointListFingerprint:s.endpointsFp,state:s.state};}
function authStatus_(x){const id=uuid_(x.sessionId),d=fp_(x.deviceId);if(!session_(id))throw err_(404,'Sessão indisponível.');const r=rows_('names').find(v=>v[0]===id&&v[1]===d);return {ok:true,sessionId:id,deviceId:d,status:r?r[4]:'unknown'};}
function receipt_(x){const id=uuid_(x.sessionId),d=fp_(x.deviceId),value=String(x.id||'');if(!session_(id))throw err_(404,'Sessão indisponível.');const found=x.type==='NAME_REQUEST'?rows_('names').some(r=>r[0]===id&&r[1]===d&&r[5]===value):x.type==='VOTE'?rows_('votes').some(r=>r[0]===id&&r[1]===d&&r[2]===value):false;return {ok:true,sessionId:id,type:x.type,id:value,deviceId:d,received:found};}
function name_(x){const m=x.message||{},id=uuid_(x.sessionId);if(!session_(id))throw err_(404,'Sessão indisponível.');device_(m,id,'NAME_REQUEST');const name=String(m.name||'').normalize('NFC').trim();if(name.length<2||name.length>120)throw err_(400,'Solicitação inválida.');return lock_(()=>{const all=rows_('names'),i=all.findIndex(r=>r[0]===id&&r[1]===m.deviceId),row=[id,m.deviceId,name,JSON.stringify(m.deviceSigningPublicKeyJwk),'pending',String(m.requestId),new Date().toISOString()];if(i>=0){if(all[i][5]===row[5]&&all[i][2]===name)return {ok:true,duplicate:true,sessionId:id,id:row[5]};set_('names',i+2,row);}else{if(all.filter(r=>r[0]===id).length>=MAX)throw err_(429,'Limite atingido.');add_('names',row);}return {ok:true,duplicate:false,sessionId:id,id:row[5]};});}
function vote_(x){const m=x.message||{},id=uuid_(x.sessionId),s=session_(id);if(!s)throw err_(404,'Sessão indisponível.');device_(m,id,'VOTE');if(m.keyFingerprint!==s.rsaFp)throw err_(409,'Configuração inválida.');return lock_(()=>{const p=rows_('names').find(r=>r[0]===id&&r[1]===m.deviceId);if(!p||p[4]!=='approved'||p[3]!==JSON.stringify(m.deviceSigningPublicKeyJwk))throw err_(403,'Publicação não autorizada.');const all=rows_('votes'),old=all.find(r=>r[0]===id&&(r[1]===m.deviceId||r[2]===m.ballotId));if(old){if(old[1]===m.deviceId&&old[2]===m.ballotId&&old[4]===JSON.stringify(m))return {ok:true,duplicate:true,sessionId:id,id:m.ballotId};throw err_(409,'Voto conflitante.');}if(all.filter(r=>r[0]===id).length>=MAX)throw err_(429,'Limite atingido.');add_('votes',[id,m.deviceId,m.ballotId,m.keyFingerprint,JSON.stringify(m),new Date().toISOString()]);return {ok:true,duplicate:false,sessionId:id,id:m.ballotId};});}
function listNames_(x){return {ok:true,sessionId:x.sessionId,records:rows_('names').filter(r=>r[0]===x.sessionId).map(r=>({deviceId:r[1],name:r[2],deviceSigningPublicKeyJwk:JSON.parse(r[3]),status:r[4],requestId:r[5],updatedAt:r[6]}))};}
function decision_(x,status){const a=rows_('names'),device=fp_(x.deviceId),i=a.findIndex(r=>r[0]===x.sessionId&&r[1]===device);if(i<0){if(!x.name||!x.deviceSigningPublicKeyJwk||sha_(canon_(x.deviceSigningPublicKeyJwk))!==device)throw err_(404,'Solicitação indisponível.');add_('names',[x.sessionId,device,String(x.name).slice(0,120),JSON.stringify(x.deviceSigningPublicKeyJwk),status,String(x.sourceRequestId||''),new Date().toISOString()]);}else{a[i][4]=status;a[i][6]=new Date().toISOString();set_('names',i+2,a[i]);}return {ok:true,sessionId:x.sessionId,deviceId:device,status};}
function listVotes_(x){return {ok:true,sessionId:x.sessionId,records:rows_('votes').filter(r=>r[0]===x.sessionId).map(r=>JSON.parse(r[4]))};}
function status_(x,s){return {ok:true,sessionId:s.id,state:s.state,names:rows_('names').filter(r=>r[0]===s.id).length,votes:rows_('votes').filter(r=>r[0]===s.id).length};}
function issuePanel_(x){cap_(x.panelCapability);const t=Date.parse(x.expiresAt);if(!Number.isFinite(t)||t<=Date.now()||t>Date.now()+86400000)throw err_(400,'Validade inválida.');add_('panels',[x.sessionId,sha_(x.panelCapability),new Date(t).toISOString(),'']);return {ok:true,sessionId:x.sessionId,expiresAt:new Date(t).toISOString()};}
function revokePanel_(x){const h=sha_(String(x.panelCapability||'')),a=rows_('panels'),i=a.findIndex(r=>r[0]===x.sessionId&&same_(r[1],h));if(i>=0){a[i][3]=new Date().toISOString();set_('panels',i+2,a[i]);}return {ok:true,sessionId:x.sessionId};}
function panel_(x){const id=uuid_(x.sessionId),h=sha_(String(x.panelCapability||'')),p=rows_('panels').find(r=>r[0]===id&&same_(r[1],h)&&!r[3]&&Date.parse(r[2])>Date.now());if(!p)throw err_(403,'Autorização inválida.');const voted=new Set(rows_('votes').filter(r=>r[0]===id).map(r=>r[1])),people=rows_('names').filter(r=>r[0]===id&&r[4]==='approved').map(r=>({name:r[2],received:voted.has(r[1])}));return {ok:true,sessionId:id,people,totalReceived:people.filter(p=>p.received).length,totalAuthorized:people.length};}
function device_(m,id,type){if(m.protocolVersion!==V||m.sessionId!==id||m.type!==type||!m.deviceSigningPublicKeyJwk||sha_(canon_(m.deviceSigningPublicKeyJwk))!==m.deviceId||m.signingKeyFingerprint!==m.deviceId||!verify_(m,m.deviceSigningPublicKeyJwk))throw err_(403,'Publicação inválida.');}
function fresh_(x){uuid_(x.sessionId);const issued=Date.parse(x.issuedAt);if(!x.requestId||!x.nonce||!Number.isFinite(issued)||Math.abs(Date.now()-issued)>CLOCK)throw err_(403,'Autorização inválida.');}function nonce_(id,n){const now=Date.now(),h=sha_(n),a=rows_('nonces');if(a.some(r=>r[0]===id&&same_(r[1],h)&&Number(r[2])>now))throw err_(403,'Autorização inválida.');add_('nonces',[id,h,String(now+900000)]);}
function session_(id){const r=rows_('sessions').find(x=>x[0]===id);return r&&{id:r[0],capHash:r[1],jwk:JSON.parse(r[2]),signFp:r[3],rsaPem:r[4],rsaFp:r[5],endpointsFp:r[6],state:r[7]};}function audit_(id,x,result){add_('audit',[id,new Date().toISOString(),x.action,x.requestId,x.adminSigningKeyFingerprint||session_(id).signFp,result]);}
function tab_(n,create){const ss=book_();let s=ss.getSheetByName(n);if(!s&&create){s=ss.insertSheet(n);s.getRange(1,1,1,TABLES[n].length).setValues([TABLES[n]]);s.setFrozenRows(1);}if(!s)throw err_(500,'Endpoint não configurado.');return s;}function rows_(n){const s=tab_(n),z=s.getLastRow();return z<2?[]:s.getRange(2,1,z-1,TABLES[n].length).getDisplayValues();}function add_(n,r){const s=tab_(n);s.getRange(s.getLastRow()+1,1,1,TABLES[n].length).setNumberFormat('@').setValues([r]);}function set_(n,row,v){tab_(n).getRange(row,1,1,TABLES[n].length).setNumberFormat('@').setValues([v]);}function book_(){const id=PropertiesService.getScriptProperties().getProperty('SPREADSHEET_ID');if(!id)throw err_(500,'Execute configurar().');return SpreadsheetApp.openById(id);}function lock_(fn){const l=LockService.getScriptLock();if(!l.tryLock(25000))throw err_(503,'Canal ocupado.');try{return fn();}finally{l.releaseLock();}}
function uuid_(v){const s=String(v||'').toLowerCase();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(s))throw err_(400,'UUID inválido.');return s;}function fp_(v){v=String(v||'');if(!/^[\w-]{43}$/.test(v))throw err_(400,'Identificador inválido.');return v;}function cap_(v){if(!/^[\w-]{43}$/.test(String(v||'')))throw err_(400,'Capacidade inválida.');}function sha_(v){const d=typeof v==='string'?Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,v,Utilities.Charset.UTF_8):Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,Utilities.newBlob(v).getBytes());return Utilities.base64EncodeWebSafe(d).replace(/=+$/,'');}function pem_(p){const m=String(p||'').match(/BEGIN PUBLIC KEY-----\s*([\w+/=\s]+)-----END PUBLIC KEY/);if(!m)throw err_(400,'Chave inválida.');return Utilities.base64Decode(m[1].replace(/\s/g,''));}function same_(a,b){a=String(a);b=String(b);let d=a.length^b.length;for(let i=0;i<Math.max(a.length,b.length);i++)d|=(a.charCodeAt(i)||0)^(b.charCodeAt(i)||0);return d===0;}function canon_(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return '['+v.map(canon_).join(',')+']';return '{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canon_(v[k])).join(',')+'}';}
/* ECDSA P-256 para assinaturas WebCrypto r||s. */
function verify_(o,j){
  try{
    const c=JSON.parse(JSON.stringify(o));delete c.signature;
    const q=Utilities.base64DecodeWebSafe(o.signature),x=bi_(Utilities.base64DecodeWebSafe(j.x)),y=bi_(Utilities.base64DecodeWebSafe(j.y));
    const n=BigInt('0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551'),one=BigInt(1),r=bi_(q.slice(0,32)),s=bi_(q.slice(32));
    if(q.length!==64||r<one||r>=n||s<one||s>=n||!curve_(x,y))return false;
    const z=bi_(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,canon_(c),Utilities.Charset.UTF_8)),w=inv_(s,n),p=add_(mul_(mod_(z*w,n),G_()),mul_(mod_(r*w,n),{x:x,y:y}));
    return !!p&&mod_(p.x,n)===r;
  }catch(_){return false;}
}
function bi_(a){return BigInt('0x'+(a.map(b=>(b&255).toString(16).padStart(2,'0')).join('')||'0'));}
function mod_(a,m){a%=m;return a<BigInt(0)?a+m:a;}
function inv_(a,m){let b=m,x=BigInt(1),y=BigInt(0);while(b){const q=a/b;[a,b]=[b,a%b];[x,y]=[y,x-q*y];}return mod_(x,m);}
function G_(){return{x:BigInt('0x6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296'),y:BigInt('0x4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5')};}
function curve_(x,y){const p=BigInt('0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff'),b=BigInt('0x5ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b'),three=BigInt(3);return mod_(y*y,p)===mod_(x*x*x-three*x+b,p);}
function add_(a,b){if(!a)return b;if(!b)return a;const p=BigInt('0xffffffff00000001000000000000000000000000ffffffffffffffffffffffff'),zero=BigInt(0),two=BigInt(2),three=BigInt(3);if(a.x===b.x&&mod_(a.y+b.y,p)===zero)return null;const l=a.x===b.x?mod_((three*a.x*a.x-three)*inv_(mod_(two*a.y,p),p),p):mod_((b.y-a.y)*inv_(mod_(b.x-a.x,p),p),p),x=mod_(l*l-a.x-b.x,p);return{x:x,y:mod_(l*(a.x-x)-a.y,p)};}
function mul_(k,p){let r=null;const one=BigInt(1);while(k){if(k&one)r=add_(r,p);p=add_(p,p);k>>=one;}return r;}
function err_(s,m){const e=Error(m);e.status=s;return e;}function reply_(fn){let x;try{x=fn();}catch(e){x={ok:false,status:e.status||500,error:e.status===403?'Autorização inválida.':e.message};}return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
