import {sessionFromLocation,storage,deviceKeys,keyFingerprint,messageBase,sign,publish,history,trustedConfigs,fetchSheet,validName,shuffle,encryptVote,saneMessage,verify,el} from '../shared/common.js';
const session=sessionFromLocation({fingerprint:true});if(session)boot(session);
async function boot({uuid,trust}){
 const app=document.querySelector('#app'),cache=storage(uuid);let cfg=null,ballot=null,device=null,answers={},questionIndex=0,busy=false,timer=null;
 const main=el('main'),live=el('p',{class:'status','aria-live':'polite'});app.append(main);
 const render=(...nodes)=>main.replaceChildren(...nodes,live);
 function header(){return [el('div',{class:'eyebrow',text:'Votação segura'}),el('h1',{text:'Sua participação'}),el('p',{text:`Sessão ${uuid}`})];}
 function fail(message='A votação está pausada ou o administrador ainda não iniciou a votação.'){render(...header(),el('section',{class:'card'},el('p',{class:'error',text:message}),el('button',{type:'button',class:'secondary',text:'Atualizar',onClick:start})));}
 async function sync(){const msgs=await history(uuid),remote=await trustedConfigs(msgs,uuid,trust);if(remote.publicKey){cache.set('publicKey',remote.publicKey.publicKeyPem);cache.put('remotePublic',remote.publicKey);}if(remote.spreadsheet){cache.put('remoteSheet',remote.spreadsheet);cache.set('sheetId',remote.spreadsheet.sheetId);cache.set('sheetGid',remote.spreadsheet.sheetGid);}const pub=remote.publicKey||cache.json('remotePublic'),sheet=remote.spreadsheet||cache.json('remoteSheet');if(!pub||!sheet)throw Error('configuração indisponível');cfg={pub,sheet,msgs};ballot=await fetchSheet(sheet.sheetId,sheet.sheetGid);if(ballot.ballotFingerprint!==sheet.ballotFingerprint)throw Error('cédula alterada');return msgs;}
 async function start(){if(busy)return;busy=true;live.textContent='Carregando configuração…';try{await sync();device=await deviceKeys(cache);const savedName=cache.get('voterName');if(ballot.state!=='1'&&ballot.state!=='0')throw Error();if(savedName){const auth=ballot.validated.find(v=>v.deviceId===device.deviceId&&v.name===savedName);auth?await waiting():nameForm(savedName);}else nameForm('');}catch{fail();}finally{busy=false;live.textContent='';}}
 function landing(){const startBtn=el('button',{type:'button',text:'Iniciar votação',onClick:start});render(el('section',{class:'hero'},...header(),el('p',{text:'Seu voto será criptografado antes de sair deste aparelho.'}),startBtn));}
 function nameForm(value){const input=el('input',{id:'full-name',autocomplete:'name',value}),send=el('button',{type:'button',text:'Enviar para validação'}),out=el('p',{class:'status','aria-live':'polite'});input.value=value;send.onclick=async()=>{send.disabled=true;try{const name=validName(input.value);device=device||await deviceKeys(cache);let msg={...messageBase('NAME_REQUEST',uuid,device.deviceId),requestId:crypto.randomUUID(),deviceId:device.deviceId,deviceSigningPublicKeyJwk:device.pub,name};await sign(msg,device.priv);await publish(uuid,msg);cache.set('voterName',name);requested(name);}catch(e){out.className='status error';out.textContent=e.message;}finally{send.disabled=false;}};render(...header(),el('section',{class:'card'},el('h2',{text:'Identificação'}),el('label',{for:'full-name',text:'Nome completo'}),input,send,out));input.focus();}
 function requested(name){const edit=el('button',{type:'button',class:'secondary',text:'Editar nome',onClick:()=>nameForm(name)}),update=el('button',{type:'button',text:'Atualizar',onClick:waiting});render(...header(),el('section',{class:'card'},el('p',{text:'Aguarde o administrador validar seu nome para a votação'}),el('div',{class:'actions'},edit,update)));setTimeout(waiting,5000);}
 async function waiting(){if(busy)return;busy=true;clearInterval(timer);try{await sync();const name=cache.get('voterName'),auth=ballot.validated.some(v=>v.deviceId===device.deviceId&&v.name===name);if(!auth){requested(name);return;}if(ballot.state==='1'){renderQuestion(0);return;}let seconds=20;const count=el('div',{class:'countdown',text:seconds}),update=el('button',{type:'button',class:'secondary',text:'↻ Atualizar',onClick:waiting});render(...header(),el('section',{class:'card'},el('h2',{text:'Aguardando o administrador iniciar a votação'}),count,update));timer=setInterval(()=>{seconds--;count.textContent=seconds;if(seconds<=0){clearInterval(timer);waiting();}},1000);}catch{fail();}finally{busy=false;}}
 function renderQuestion(index){questionIndex=index;const q=ballot.questions[index],opts=q.shuffle?shuffle(q.options):q.options,chosen=new Set(answers[q.id]||[]),progress=el('div',{class:'progress'},el('span',{style:`width:${((index+1)/ballot.questions.length)*100}%`})),form=el('div',{class:'question-options'}),out=el('p',{class:'status error','aria-live':'polite'});for(const o of opts){const input=el('input',{type:q.count===1?'radio':'checkbox',name:'answer',value:o.id});input.checked=chosen.has(o.id);input.onchange=()=>{let vals=[...form.querySelectorAll('input:checked')].map(x=>x.value);if(vals.length>q.count){input.checked=false;out.textContent=`Escolha exatamente ${q.count} opções.`;return;}answers[q.id]=vals;out.textContent='';};form.append(el('label',{class:'option'},input,el('span',{text:o.text})));}const next=el('button',{type:'button',text:index===ballot.questions.length-1?'Verificar':'Próxima'});next.onclick=()=>{if((answers[q.id]||[]).length!==q.count){out.textContent=`Escolha exatamente ${q.count} ${q.count===1?'opção':'opções'}.`;return;}index===ballot.questions.length-1?review():renderQuestion(index+1);};render(...header(),progress,el('section',{class:'card'},el('p',{class:'eyebrow',text:`Pergunta ${index+1} de ${ballot.questions.length}`}),el('h2',{text:q.text}),el('p',{text:q.count===1?'Escolha uma opção.':`Escolha ${q.count} opções.`}),form,out,next));}
 function review(){const card=el('section',{class:'card'},el('h2',{text:'Verifique seu voto'}));ballot.questions.forEach((q,i)=>{const selected=q.options.filter(o=>(answers[q.id]||[]).includes(o.id)).map(o=>o.text).join(', '),edit=el('button',{type:'button',class:'secondary',text:'Editar',onClick:()=>renderQuestion(i)});card.append(el('div',{class:'review-item'},el('strong',{text:q.text}),el('p',{text:selected}),edit));});card.append(el('button',{type:'button',class:'success',text:'Confirmar Votação',onClick:confirmVote}));render(...header(),card);}
 async function confirmVote(e){if(busy)return;busy=true;e.currentTarget.disabled=true;render(...header(),el('section',{class:'card'},el('span',{class:'spinner'}),el('p',{text:'Confirmando que seu voto foi computado'})));try{const oldFingerprint=ballot.ballotFingerprint;await sync();if(ballot.state!=='1'||ballot.ballotFingerprint!==oldFingerprint)throw Error('A votação foi pausada ou a cédula mudou.');device=device||await deviceKeys(cache);let state=cache.json('ballotState');const ballotId=state?.ballotId||crypto.randomUUID();cache.put('ballotState',{ballotId,status:'sending'});const payload={protocolVersion:1,sessionId:uuid,ballotId,deviceId:device.deviceId,voterName:cache.get('voterName'),sheetId:cfg.sheet.sheetId,ballotFingerprint:ballot.ballotFingerprint,submittedAt:new Date().toISOString(),answers:ballot.questions.map(q=>({questionId:q.id,optionIds:answers[q.id]}))},encrypted=await encryptVote(payload,cfg.pub.publicKeyPem);let msg={...messageBase('VOTE',uuid,device.deviceId),ballotId,deviceId:device.deviceId,keyFingerprint:cfg.pub.fingerprint,keyAlgorithm:'RSA-OAEP-256',contentAlgorithm:'A256GCM',...encrypted,deviceSigningPublicKeyJwk:device.pub};await sign(msg,device.priv);await publish(uuid,msg);let found=false;for(let i=0;i<6&&!found;i++){const msgs=await history(uuid);found=msgs.some(x=>x.type==='VOTE'&&x.ballotId===ballotId&&x.deviceId===device.deviceId);if(!found)await new Promise(r=>setTimeout(r,1500));}if(!found)throw Error('O envio ocorreu, mas ainda não foi confirmado. Tente verificar novamente.');cache.put('ballotState',{ballotId,status:'confirmed'});answers={};render(...header(),el('section',{class:'card confirmed'},el('div',{class:'check','aria-hidden':'true',text:'✓'}),el('h2',{text:'Voto confirmado'}),el('p',{text:'Seu voto criptografado foi localizado no sistema.'})));}catch(err){render(...header(),el('section',{class:'card'},el('p',{class:'error',text:err.message}),el('button',{type:'button',text:'Tentar novamente',onClick:()=>confirmVote({currentTarget:{disabled:false}})})));}finally{busy=false;}}
 if(cache.json('ballotState')?.status==='confirmed')render(...header(),el('section',{class:'card confirmed'},el('div',{class:'check',text:'✓'}),el('h2',{text:'Voto confirmado'})));else landing();
}
