import {sessionFromLocation,storage,saveEndpointsCache,loadEndpointsCache,deviceKeys,keyFingerprint,messageBase,sign,publish,history,trustedConfigs,fetchSheetCached,validName,shuffle,encryptVote,assignedEndpoint,el} from '../shared/common.js';
const session=sessionFromLocation({fingerprint:true,sheet:true});if(session)boot(session);
async function boot({uuid,trust,sheetId}){
 const app=document.querySelector('#app'),cache=storage(uuid);let cfg=null,ballot=null,device=null,answers={},questionIndex=0,busy=false,timer=null;
 const fetchSheet=id=>fetchSheetCached(id,cache,{force:ballot!==null&&Object.keys(answers).length>0});
 let transport;
 const main=el('main'),live=el('p',{class:'status','aria-live':'polite'});app.append(main);
 const render=(...nodes)=>main.replaceChildren(...nodes,live);
 function header(){return [el('div',{class:'eyebrow',text:'Votação segura'}),el('h1',{text:'Sua participação'}),el('p',{text:`Sessão ${uuid}`})];}
 function fail(error){
  const message=error instanceof Error&&error.message.trim()?error.message:'Não foi possível identificar a causa da falha.';
  const details=el('details',{class:'error-details'},el('summary',{text:'Ver detalhes técnicos'}),el('p',{text:message}));
  render(...header(),el('section',{class:'card'},el('p',{class:'error',text:'A votação está pausada ou o administrador ainda não iniciou a votação.'}),details,el('button',{type:'button',class:'secondary',text:'Atualizar',onClick:start})));
 }
 async function sync(){const previous=await loadEndpointsCache(cache,sheetId);ballot=await fetchSheet(sheetId);const current=await saveEndpointsCache(cache,sheetId,ballot.endpoints);device=device||await deviceKeys(cache);const assigned=await assignedEndpoint(uuid,device.deviceId,current.endpoints),savedFp=cache.get('endpointFingerprint')||previous?.fingerprint,published=cache.get('requestId')||cache.json('ballotState');if(savedFp&&savedFp!==assigned.fingerprint&&published)throw Error('A lista de endpoints mudou; procure o administrador.');transport=cache.get('endpoint')||assigned.endpoint;if(!current.endpoints.includes(transport))throw Error('O endpoint vinculado não existe mais.');cache.set('endpoint',transport);cache.set('endpointFingerprint',assigned.fingerprint);const msgs=await history(uuid,transport),remote=await trustedConfigs(msgs,uuid,trust);if(remote.publicKey){cache.set('publicKey',remote.publicKey.publicKeyPem);cache.put('remotePublic',remote.publicKey);}const pub=remote.publicKey||cache.json('remotePublic');if(!pub)throw Error('configuração indisponível');cfg={pub,msgs};return msgs;}
 async function start(){if(busy)return;busy=true;live.textContent='Carregando configuração…';try{await sync();device=await deviceKeys(cache);const savedName=cache.get('voterName');if(ballot.state!=='1'&&ballot.state!=='0')throw Error('O estado da votação na planilha é inválido.');if(savedName){const auth=ballot.validated.find(v=>v.deviceId===device.deviceId&&v.name===savedName);auth?setTimeout(waiting,0):nameForm(savedName);}else nameForm('');}catch(error){fail(error);}finally{busy=false;live.textContent='';}}
 function landing(){const startBtn=el('button',{type:'button',text:'Iniciar votação',onClick:start});render(el('section',{class:'hero'},...header(),el('p',{text:'Seu voto será criptografado antes de sair deste aparelho.'}),startBtn));}
 function nameForm(value){const input=el('input',{id:'full-name',autocomplete:'name',value}),send=el('button',{type:'button',text:'Enviar para validação'}),out=el('p',{class:'status','aria-live':'polite'});input.value=value;send.onclick=async()=>{send.disabled=true;try{const name=validName(input.value);device=device||await deviceKeys(cache);let msg={...messageBase('NAME_REQUEST',uuid,device.deviceId),requestId:cache.get('requestId')||crypto.randomUUID(),deviceId:device.deviceId,deviceSigningPublicKeyJwk:device.pub,name};await sign(msg,device.priv);await publish(uuid,msg,transport);cache.set('requestId',msg.requestId);cache.set('voterName',name);requested(name);}catch(e){out.className='status error';out.textContent=e.message;}finally{send.disabled=false;}};render(...header(),el('section',{class:'card'},el('h2',{text:'Identificação'}),el('label',{for:'full-name',text:'Nome completo'}),input,send,out));input.focus();}
 function requested(name){const edit=el('button',{type:'button',class:'secondary',text:'Editar nome',onClick:()=>nameForm(name)}),update=el('button',{type:'button',text:'Atualizar',onClick:waiting});render(...header(),el('section',{class:'card'},el('p',{text:'Aguarde o administrador validar seu nome para a votação'}),el('div',{class:'actions'},edit,update)));setTimeout(waiting,5000);}
 async function waiting(){if(busy)return;busy=true;clearInterval(timer);try{await sync();const name=cache.get('voterName'),auth=ballot.validated.some(v=>v.deviceId===device.deviceId&&v.name===name);if(!auth){requested(name);return;}if(ballot.state==='1'){renderQuestion(0);return;}let seconds=20;const count=el('div',{class:'countdown',text:seconds}),update=el('button',{type:'button',class:'secondary',text:'↻ Atualizar',onClick:waiting});render(...header(),el('section',{class:'card'},el('h2',{text:'Aguardando o administrador iniciar a votação'}),count,update));timer=setInterval(()=>{seconds--;count.textContent=seconds;if(seconds<=0){clearInterval(timer);waiting();}},1000);}catch(error){fail(error);}finally{busy=false;}}
 function renderQuestion(index,returnToReview=false){questionIndex=index;const q=ballot.questions[index],opts=q.shuffle?shuffle(q.options):q.options,chosen=new Set(answers[q.id]||[]),progress=el('div',{class:'progress'},el('span',{style:`width:${((index+1)/ballot.questions.length)*100}%`})),form=el('div',{class:`question-options ${q.showImages?'with-images':''}`}),out=el('p',{class:'status error','aria-live':'polite'});for(const o of opts){const input=el('input',{type:q.count===1?'radio':'checkbox',name:'answer',value:o.id});input.checked=chosen.has(o.id);input.onchange=()=>{let vals=[...form.querySelectorAll('input:checked')].map(x=>x.value);if(vals.length>q.count){input.checked=false;out.textContent=`Escolha exatamente ${q.count} opções.`;return;}answers[q.id]=vals;out.textContent='';};form.append(el('label',{class:'option'},input,q.showImages?el('img',{src:o.image,alt:'',loading:'lazy',referrerpolicy:'no-referrer'}):[],el('span',{text:o.text})));}const next=el('button',{type:'button',text:returnToReview?'Voltar à revisão':index===ballot.questions.length-1?'Verificar':'Próxima'});next.onclick=()=>{if((answers[q.id]||[]).length!==q.count){out.textContent=`Escolha exatamente ${q.count} ${q.count===1?'opção':'opções'}.`;return;}returnToReview||index===ballot.questions.length-1?review():renderQuestion(index+1);};render(...header(),progress,el('section',{class:'card'},el('p',{class:'eyebrow',text:`Pergunta ${index+1} de ${ballot.questions.length}`}),el('h2',{text:q.text}),el('p',{text:q.count===1?'Escolha uma opção.':`Escolha ${q.count} opções.`}),form,out,next));}
 function review(){const card=el('section',{class:'card'},el('h2',{text:'Verifique seu voto'}));ballot.questions.forEach((q,i)=>{const selected=q.options.filter(o=>(answers[q.id]||[]).includes(o.id)),choices=el('div',{class:'review-choices'},...selected.map(o=>el('div',{class:'review-choice'},q.showImages&&o.image?el('img',{src:o.image,alt:'',loading:'lazy',referrerpolicy:'no-referrer'}):[],el('span',{text:o.text})))),edit=el('button',{type:'button',class:'secondary',text:'Editar',onClick:()=>renderQuestion(i,true)});card.append(el('div',{class:'review-item'},el('strong',{text:q.text}),choices,edit));});card.append(el('button',{type:'button',class:'success',text:'Confirmar Votação',onClick:confirmVote}));render(...header(),card);}
 async function confirmVote(e){if(busy)return;busy=true;e.currentTarget.disabled=true;render(...header(),el('section',{class:'card'},el('span',{class:'spinner'}),el('p',{text:'Confirmando que seu voto foi computado'})));try{const oldFingerprint=ballot.ballotFingerprint;await sync();if(ballot.state!=='1'||ballot.ballotFingerprint!==oldFingerprint)throw Error('A votação foi pausada ou a cédula mudou.');let state=cache.json('ballotState');const ballotId=state?.ballotId||crypto.randomUUID();cache.put('ballotState',{ballotId,status:'sending',endpoint:transport});const payload={protocolVersion:1,sessionId:uuid,ballotId,deviceId:device.deviceId,voterName:cache.get('voterName'),sheetId,ballotFingerprint:ballot.ballotFingerprint,submittedAt:new Date().toISOString(),answers:ballot.questions.map(q=>({questionId:q.id,optionIds:answers[q.id]}))},encrypted=await encryptVote(payload,cfg.pub.publicKeyPem);let msg={...messageBase('VOTE',uuid,device.deviceId),ballotId,deviceId:device.deviceId,keyFingerprint:cfg.pub.fingerprint,keyAlgorithm:'RSA-OAEP-256',contentAlgorithm:'A256GCM',...encrypted,deviceSigningPublicKeyJwk:device.pub};await sign(msg,device.priv);await publish(uuid,msg,transport);let found=false;for(let i=0;i<6&&!found;i++){const msgs=await history(uuid,transport);found=msgs.some(x=>x.type==='VOTE'&&x.ballotId===ballotId&&x.deviceId===device.deviceId);if(!found&&i<5)await new Promise(r=>setTimeout(r,1500));}if(!found)throw Error('O envio ocorreu, mas ainda não foi confirmado. Tente verificar novamente.');cache.put('ballotState',{ballotId,status:'confirmed',endpoint:transport});answers={};render(...header(),el('section',{class:'card confirmed'},el('div',{class:'check','aria-hidden':'true',text:'✓'}),el('h2',{text:'Voto confirmado'}),el('p',{text:'Seu voto criptografado foi localizado no sistema.'})));}catch(err){render(...header(),el('section',{class:'card'},el('p',{class:'error',text:err.message}),el('button',{type:'button',text:'Tentar novamente',onClick:()=>confirmVote({currentTarget:{disabled:false}})})));}finally{busy=false;}}
 if(cache.json('ballotState')?.status==='confirmed')render(...header(),el('section',{class:'card confirmed'},el('div',{class:'check',text:'✓'}),el('h2',{text:'Voto confirmado'})));else landing();
}
