import {sessionFromLocation,storage,saveEndpointsCache,histories,trustedConfigs,fetchSheetCached,keyFingerprint,saneMessage,verify,nameDecisions,votingStart,el} from '../shared/common.js';
import {showQrLink,votingUrl} from '../shared/qr-link.js';
import {createPanelView} from './view.js';
const session=sessionFromLocation({fingerprint:true,sheet:true});if(session)boot(session);
async function fetchSheet(sheetId){const cache=storage(session.uuid),ballot=await fetchSheetCached(sheetId,cache);await saveEndpointsCache(cache,sheetId,ballot.endpoints);return ballot;}
async function boot({uuid,trust,sheetId}){const qrButton=el('button',{type:'button',text:'QR code da votação'});qrButton.onclick=()=>showQrLink('Página de Votação',votingUrl({uuid,sheetId,trust}),qrButton,{large:true});const {states,status,countdown,render}=createPanelView(document.querySelector('#app'),{action:qrButton});let green=new Set(),lastPeople=[],running=false,timer=null;
 function schedule(){let seconds=5;countdown.textContent=`Próxima atualização em ${seconds} s`;timer=setInterval(()=>{seconds--;if(seconds===0){clearInterval(timer);timer=null;cycle();}else countdown.textContent=`Próxima atualização em ${seconds} s`;},1000);}
 async function cycle(){if(running)return;running=true;countdown.textContent='Atualizando…';try{const ballot=await fetchSheet(sheetId),aggregate=await histories(uuid,ballot.endpoints);states.replaceChildren(...aggregate.channels.map((c,i)=>el('span',{class:`channel ${c.status}`,text:`Endpoint ${i+1}: ${c.status==='updated'?'atualizado':'falha'}`})));const configured=[];for(const c of aggregate.channels)if(c.status==='updated')configured.push(await trustedConfigs(c.messages,uuid,trust));if(!aggregate.complete||configured.some(c=>!c.publicKey)||new Set(configured.map(c=>c.publicKey.signature)).size!==1)throw Error('Os endpoints ainda não possuem chave pública íntegra e idêntica.');const decisions=await nameDecisions(aggregate.messages,uuid,trust),requests=new Map();for(const request of aggregate.messages)if(request.type==='NAME_REQUEST'&&saneMessage(request,uuid,'NAME_REQUEST')&&request.deviceSigningPublicKeyJwk&&request.deviceId===await keyFingerprint(request.deviceSigningPublicKeyJwk)&&await verify(request,request.deviceSigningPublicKeyJwk))requests.set(request.deviceId,request);const allowed=new Map([...requests.values()].filter(request=>decisions.get(request.requestId)?.decision==='approved').map(request=>[request.deviceId,{deviceId:request.deviceId,name:request.name}])),starts=new Map();for(const channel of aggregate.channels)starts.set(channel.endpoint,await votingStart(channel.messages,uuid,trust,ballot.ballotFingerprint));const locations=new Map(),ballots=new Map(),conflicts=new Set();green=new Set();for(const m of aggregate.messages){if(m.type!=='VOTE'||!allowed.has(m.deviceId)||!starts.get(m._endpoint)||m._cursor<=starts.get(m._endpoint)._cursor||!saneMessage(m,uuid,'VOTE')||!m.deviceSigningPublicKeyJwk)continue;const fingerprint=await keyFingerprint(m.deviceSigningPublicKeyJwk),signatureValid=await verify(m,m.deviceSigningPublicKeyJwk);if(fingerprint!==m.deviceId||m.signingKeyFingerprint!==m.deviceId||!signatureValid)continue;const previous=locations.get(m.deviceId),oldBallot=ballots.get(m.ballotId);if((previous&&previous!==m._endpoint)||(oldBallot&&oldBallot!==m._endpoint)){conflicts.add(m.deviceId);continue;}locations.set(m.deviceId,m._endpoint);ballots.set(m.ballotId,m._endpoint);green.add(m.deviceId);}for(const id of conflicts)green.delete(id);lastPeople=[...allowed.values()];render(lastPeople,green);status.className='status';status.textContent='Totais consolidados de todos os endpoints.';}catch(e){render(lastPeople,green);status.className='status operational';status.textContent=`Total provisório. ${e.message}`;}finally{running=false;schedule();}}
 await cycle();
}
