import {UUID_RE,sessionFromLocation,storage,generateKeys,keyFingerprint,sha,depem,assertRsaPair,parseSheetUrl,fetchSheet,fetchWithTimeout,decryptVote,endpointFingerprint,randomCapability,registerAll,adminAll,publicApi,b64,unb64,te,td,el,modal} from '../shared/common.js';
import {showQrLink} from '../shared/qr-link.js';
const app=document.querySelector('#app'),p=new URLSearchParams(location.search),uv=p.getAll('uuid'),sv=p.getAll('sheet-id');
if(!uv.length&&!sv.length)step1();else{const s=sessionFromLocation({sheet:sv.length>0});s?(sv.length?boot(s):step2(s.uuid)):unauthorized('Endereço inválido.');}
function frame(title,...n){app.replaceChildren(el('main',{},el('div',{class:'eyebrow',text:'Administração segura'}),el('h1',{text:title}),...n));}function save(c,o){for(const[k,v]of Object.entries(o))typeof v==='string'?c.set(k,v):c.put(k,v);}
function step1(){const b=el('button',{type:'button',text:'Criar sessão segura'}),out=el('p',{class:'status'});b.onclick=async()=>{b.disabled=true;try{const id=crypto.randomUUID().toLowerCase();if(!UUID_RE.test(id))throw Error('UUID inválido.');const c=storage(id);save(c,{...await generateKeys(),adminCapability:randomCapability()});location.replace(`?uuid=${id}`);}catch(e){out.textContent=e.message;b.disabled=false;}};frame('1º Passo',el('section',{class:'card'},el('p',{text:'A autoridade será criada somente neste navegador.'}),b,out));}
function step2(uuid){const input=el('input',{type:'url',placeholder:'URL da Planilha Google'}),b=el('button',{type:'button',text:'Validar planilha'}),out=el('p',{class:'status'});b.onclick=async()=>{b.disabled=true;try{const{sheetId}=parseSheetUrl(input.value),ballot=await fetchSheet(sheetId);await Promise.all(ballot.endpoints.map(async e=>{const r=await fetchWithTimeout(`${e}?action=health`,{cache:'no-store'});let x;try{x=await r.json();}catch{throw Error(`O endpoint ${e} não retornou JSON.`);}if(!r.ok||!x?.ok||x.protocolVersion!==2)throw Error(`O endpoint ${e} não está disponível no protocolo 2.`);}));location.replace(`?uuid=${uuid}&sheet-id=${encodeURIComponent(sheetId)}`);}catch(e){out.className='status error';out.textContent=e.message||'Planilha ou endpoint v2 indisponível.';b.disabled=false;}};frame('2º Passo',el('section',{class:'card'},input,b,out));}
function unauthorized(msg='Este aparelho não está autorizado a administrar esta sessão.'){const file=el('input',{type:'file',accept:'application/json'}),pass=el('input',{type:'password',placeholder:'Senha do backup'}),b=el('button',{type:'button',text:'Restaurar backup cifrado'}),out=el('p',{class:'status'});b.onclick=async()=>{try{const x=await decryptBackup(await file.files[0].text(),pass.value);save(storage(x.sessionId),x.secrets);location.replace(x.url);}catch{out.className='status error';out.textContent='Backup ou senha inválidos.';}};frame('Aparelho não autorizado',el('section',{class:'card'},el('p',{class:'error',text:msg}),file,pass,b,out));}
async function boot({uuid,sheetId}){const c=storage(uuid),cap=c.get('adminCapability'),priv=c.json('adminSigningPrivateKey');if(!cap||!priv)return unauthorized();let ballot;try{ballot=await fetchSheet(sheetId);}catch(e){return frame('Sessão indisponível',el('p',{class:'error',text:e.message}));}const status=el('p',{class:'status','aria-live':'polite'}),ops=el('div');frame('Administração',el('section',{class:'card'},el('p',{text:`Sessão ${uuid}`}),status),ops);const keys=()=>({publicKey:c.get('publicKey'),privateKey:c.get('privateKey'),adminSigningPublicKey:c.json('adminSigningPublicKey'),adminSigningPrivateKey:c.json('adminSigningPrivateKey')}),request=(action,data={})=>adminAll(ballot.endpoints,action,uuid,cap,priv,data);
 async function registered(){try{const fp=await keyFingerprint(keys().adminSigningPublicKey),ef=await endpointFingerprint(ballot.endpoints),a=await Promise.all(ballot.endpoints.map(e=>publicApi(e,'publicConfig',{sessionId:uuid})));return a.every(x=>x.adminSigningKeyFingerprint===fp&&x.endpointListFingerprint===ef);}catch{return false;}}
 async function render(){ops.replaceChildren();if(!await registered()){const b=el('button',{type:'button',text:'Registrar sessão em todos os endpoints'});b.onclick=async()=>{b.disabled=true;try{const k=keys();await assertRsaPair(k.publicKey,k.privateKey);await registerAll(ballot.endpoints,{sessionId:uuid,adminCapability:cap,adminSigningPublicKeyJwk:k.adminSigningPublicKey,adminSigningKeyFingerprint:await keyFingerprint(k.adminSigningPublicKey),encryptionPublicKeyPem:k.publicKey,encryptionKeyFingerprint:await sha(depem(k.publicKey,'PUBLIC KEY')),endpointListFingerprint:await endpointFingerprint(ballot.endpoints)},k.adminSigningPrivateKey);status.className='status ok';status.textContent='Registro convergente.';await render();}catch(e){status.className='status error';status.textContent=e.message+' Em caso de conflito, crie outro UUID.';}finally{b.disabled=false;}};ops.append(el('section',{class:'card'},el('h2',{text:'Registro pendente'}),el('p',{text:'QR, painel, validação e apuração estão bloqueados.'}),b));return;}
 const stateText=el('p',{class:'status','aria-live':'polite'}),start=el('button',{type:'button',class:'success',text:'Iniciar votação'}),pause=el('button',{type:'button',class:'secondary',text:'Pausar votação'}),backup=el('button',{type:'button',text:'Backup cifrado'}),people=el('button',{type:'button',text:'Validar pessoas'}),vote=el('button',{type:'button',text:'Página de votação'}),panel=el('button',{type:'button',text:'Emitir painel'}),results=el('button',{type:'button',text:'Resultados'});ops.append(el('section',{class:'card'},el('h2',{text:'Estado da votação'}),stateText,el('div',{class:'actions'},start,pause)),el('section',{class:'card'},el('div',{class:'actions'},backup,people,vote,panel,results)));
 async function refreshState(){try{const configs=await Promise.all(ballot.endpoints.map(e=>publicApi(e,'publicConfig',{sessionId:uuid}))),states=new Set(configs.map(x=>x.state));if(states.size!==1)throw Error('Os endpoints estão com estados divergentes. Repita a ação desejada para reconvergir.');const state=configs[0].state;if(!['active','paused'].includes(state))throw Error('Estado inválido no endpoint.');stateText.className=`status ${state==='active'?'ok':''}`;stateText.textContent=state==='active'?'Votação aberta para recebimento de votos.':'Votação pausada.';start.disabled=state==='active';pause.disabled=state==='paused';}catch(e){stateText.className='status error';stateText.textContent=e.message;start.disabled=pause.disabled=false;}}
 async function changeState(state){start.disabled=pause.disabled=true;try{await request('setSessionState',{state});status.className='status ok';status.textContent=state==='active'?'Votação iniciada em todos os endpoints.':'Votação pausada em todos os endpoints.';}catch(e){status.className='status error';status.textContent=e.message;}finally{await refreshState();}}
 start.onclick=()=>changeState('active');pause.onclick=()=>changeState('paused');await refreshState();
 backup.onclick=()=>backupDialog(backup);people.onclick=()=>peopleDialog(people);vote.onclick=async()=>link('Página de votação','../cliente/','k',await keyFingerprint(keys().adminSigningPublicKey),vote);panel.onclick=async()=>{try{const pc=randomCapability(),expiresAt=new Date(Date.now()+28800000).toISOString();await request('issuePanelCapability',{panelCapability:pc,expiresAt});link('Painel somente leitura','../painel/','panel',pc,panel);}catch(e){status.textContent=e.message;}};results.onclick=()=>resultsDialog(results);
 }
 function link(title,path,key,value,opener){const u=new URL(path,location.href);u.search=`?uuid=${uuid}&sheet-id=${encodeURIComponent(sheetId)}`;u.hash=`${key}=${value}`;showQrLink(title,u,opener);}
 function backupDialog(opener){const pass=el('input',{type:'password',placeholder:'Senha (mínimo 12 caracteres)'}),go=el('button',{type:'button',text:'Gerar'}),out=el('p',{class:'status'});modal('Backup cifrado',el('div',{},pass,go,out),opener);go.onclick=async()=>{try{if(pass.value.length<12)throw Error('Senha muito curta.');const data=await encryptBackup({sessionId:uuid,url:location.href,secrets:{...keys(),adminCapability:cap}},pass.value),a=el('a',{href:URL.createObjectURL(new Blob([JSON.stringify(data)])),download:`eleicao-${uuid}.backup.json`,text:'Baixar backup'});out.replaceWith(a);}catch(e){out.textContent=e.message;}};}
 async function peopleDialog(opener){const box=el('div',{},'Carregando…');modal('Validação privada',box,opener);try{const responses=await request('listNameRequests'),records=new Map();for(const r of responses)for(const p of r.records)records.set(p.deviceId,p);box.replaceChildren(...[...records.values()].map(p=>{const row=el('div',{class:'request'},el('span',{text:`${p.name} — ${p.status}`}));for(const[label,action]of[['Aprovar','approveDevice'],['Rejeitar','rejectDevice'],['Revogar','revokeDevice']])row.append(el('button',{type:'button',class:'secondary',text:label,onClick:async()=>{await request(action,{deviceId:p.deviceId,name:p.name,deviceSigningPublicKeyJwk:p.deviceSigningPublicKeyJwk,sourceRequestId:p.requestId});box.remove();peopleDialog(opener);}}));return row;}));if(!records.size)box.append('Nenhuma solicitação.');}catch(e){box.replaceChildren(el('p',{class:'error',text:e.message}));}}
 async function resultsDialog(opener){const box=el('div',{},'Decifrando localmente…');modal('Resultados',box,opener);try{const sets=await request('listEncryptedVotes'),votes=new Map();for(const s of sets)for(const m of s.records)votes.set(m.ballotId,m);const counts=new Map(ballot.questions.map(q=>[q.id,new Map(q.options.map(o=>[o.id,0]))]));let n=0;for(const m of votes.values())try{const v=await decryptVote(m,keys().privateKey);if(v.sheetId!==sheetId||v.ballotFingerprint!==ballot.ballotFingerprint)continue;for(const q of ballot.questions){const a=v.answers.find(x=>x.questionId===q.id);if(!a||a.optionIds.length!==q.count)throw 0;for(const id of a.optionIds)counts.get(q.id).set(id,counts.get(q.id).get(id)+1);}n++;}catch{}box.replaceChildren(el('p',{class:'ok',text:`${n} votos válidos.`}),...ballot.questions.map(q=>el('section',{},el('h3',{text:q.text}),...q.options.map(o=>el('p',{text:`${o.text}: ${counts.get(q.id).get(o.id)}`})))));}catch(e){box.textContent=e.message;}}
 await render();}
async function encryptBackup(value,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),base=await crypto.subtle.importKey('raw',te.encode(password),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt']);return{version:2,iterations:310000,salt:b64(salt,true),iv:b64(iv,true),ciphertext:b64(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,te.encode(JSON.stringify(value))),true)};}
async function decryptBackup(raw,password){const b=JSON.parse(raw),base=await crypto.subtle.importKey('raw',te.encode(password),'PBKDF2',false,['deriveKey']),key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:unb64(b.salt),iterations:b.iterations,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['decrypt']);if(b.version!==2||b.iterations!==310000)throw Error();return JSON.parse(td.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(b.iv)},key,unb64(b.ciphertext))));}
