import {sessionFromLocation,storage,generateKeys,keyFingerprint,sha,depem,assertRsaPair,importRsaPublic,importRsaPrivate,importSigning,messageBase,sign,publish,history,saneMessage,verify,parseSheetUrl,fetchSheet,decryptVote,el,modal,b64,unb64,te,td} from '../shared/common.js';

const session=sessionFromLocation(); if(session) boot(session.uuid);
async function boot(uuid){
 const cache=storage(uuid), app=document.querySelector('#app'); let pending=[], locked=false, configured=false;
 app.append(el('main',{},el('div',{class:'eyebrow',text:'Administração segura'}),el('h1',{text:'Votação'}),el('p',{text:`Sessão ${uuid}`})));
 const main=app.firstChild, status=el('p',{class:'status','aria-live':'polite'});
 const gen=el('button',{type:'button',text:'Gerar Criptografia Assimétrica'}); const cryptoCard=el('section',{class:'card'},el('h2',{text:'1. Criptografia'}),gen,status); main.append(cryptoCard);
 const keysArea=el('div',{class:'key-area'}); cryptoCard.append(keysArea);
 const sheetInput=el('input',{type:'url',placeholder:'https://docs.google.com/spreadsheets/d/...'}); const sheetBtn=el('button',{type:'button',text:'Publicar Planilha'}); const sheetStatus=el('p',{class:'status','aria-live':'polite'}); const sheetCard=el('section',{class:'card'},el('h2',{text:'2. Planilha'}),el('label',{for:'sheet-url',text:'URL da planilha'}),sheetInput,sheetBtn,sheetStatus);sheetInput.id='sheet-url'; main.append(sheetCard);
 const validateBtn=el('button',{type:'button',text:'Validar Pessoas'}), votePageBtn=el('button',{type:'button',text:'Página de Votação'}), panelBtn=el('button',{type:'button',text:'Painel de Acompanhamento'}), resultsBtn=el('button',{type:'button',text:'Resultados da Votação'}); main.append(el('section',{class:'card'},el('h2',{text:'3. Operação'}),el('div',{class:'actions'},validateBtn,votePageBtn,panelBtn,resultsBtn)));
 function loadKeys(){return ['publicKey','privateKey','adminSigningPublicKey','adminSigningPrivateKey'].reduce((o,k)=>(o[k]=k.includes('Signing')?cache.json(k):cache.get(k),o),{});} 
 async function renderKeys(){keysArea.replaceChildren();const k=loadKeys(),ready=Object.values(k).every(Boolean);panelBtn.disabled=!ready;if(!ready)return;
  const privateButton=el('button',{class:'private-button',type:'button','aria-label':'Abrir chave privada'},el('span',{class:'lock','aria-hidden':'true',text:'✉🔒'}),el('span',{text:'Chave Privada'}));
  privateButton.onclick=()=>{const ta=el('textarea',{readonly:true});ta.value=k.privateKey;const copy=el('button',{type:'button',text:'Copiar chave'});copy.onclick=async()=>{await navigator.clipboard.writeText(ta.value);copy.textContent='Copiada';};const m=modal('Chave Privada',el('div',{},el('p',{class:'warning',text:'Não compartilhe essa chave, ela garante uma votação secreta e segura'}),ta,copy),privateButton);const old=m.close;m.close=()=>{ta.value='';old();};};
  const pub=el('textarea',{readonly:true});pub.value=k.publicKey;const pubStatus=el('p',{class:'status','aria-live':'polite'}),pubBtn=el('button',{type:'button',text:'Publicar Chave'});pubBtn.onclick=()=>publishPublic(pubBtn,pubStatus);
  const backup=el('button',{type:'button',class:'secondary',text:'Baixar arquivo de chaves'}),imp=el('button',{type:'button',class:'secondary',text:'Inserir chaves existentes'});backup.onclick=()=>backupKeys(backup);imp.onclick=()=>importKeys(imp);
  keysArea.append(privateButton,el('label',{text:'Chave Pública'}),pub,el('div',{class:'actions'},pubBtn,backup,imp),pubStatus);
 }
 gen.onclick=async()=>{if(locked)return alert('A rotação foi bloqueada porque já existe voto no tópico.');if(loadKeys().privateKey&&!confirm('Trocar as chaves pode tornar votos indecifráveis e invalidar assinaturas. Continuar?'))return;gen.disabled=true;gen.replaceChildren(el('span',{class:'spinner'}),' Gerando…');try{const k=await generateKeys();for(const [n,v]of Object.entries(k))typeof v==='string'?cache.set(n,v):cache.put(n,v);status.className='status ok';status.textContent='Chaves geradas e guardadas neste navegador.';await renderKeys();}catch(e){status.className='status error';status.textContent=e.message;}finally{gen.disabled=false;gen.textContent='Gerar Criptografia Assimétrica';}};
 async function admin(){const k=loadKeys();if(!Object.values(k).every(Boolean))throw new Error('Gere ou importe as chaves primeiro.');await assertRsaPair(k.publicKey,k.privateKey);const fp=await keyFingerprint(k.adminSigningPublicKey);return {...k,fp};}
 async function publishPublic(btn,out){if(locked)throw new Error('Nova chave bloqueada após o primeiro voto.');btn.disabled=true;try{const k=await admin();await importRsaPublic(k.publicKey);const fingerprint=await sha(depem(k.publicKey,'PUBLIC KEY'));let msg={...messageBase('PUBLIC_KEY',uuid,k.fp),publicKeyPem:k.publicKey,fingerprint,adminSigningPublicKeyJwk:k.adminSigningPublicKey};await sign(msg,k.adminSigningPrivateKey);await publish(uuid,msg);out.className='status ok';out.textContent='Chave pública publicada.';}catch(e){out.className='status error';out.textContent=e.message;}finally{btn.disabled=false;}}
 sheetBtn.onclick=async()=>{sheetBtn.disabled=true;try{const parsed=parseSheetUrl(sheetInput.value),ballot=await fetchSheet(parsed.sheetId,parsed.sheetGid),k=await admin();let msg={...messageBase('SPREADSHEET',uuid,k.fp),...parsed,ballotFingerprint:ballot.ballotFingerprint,adminSigningPublicKeyJwk:k.adminSigningPublicKey};await sign(msg,k.adminSigningPrivateKey);await publish(uuid,msg);for(const [n,v] of Object.entries(parsed))cache.set(n,v);sheetStatus.className='status ok';sheetStatus.textContent='Planilha validada e publicada.';}catch(e){sheetStatus.className='status error';sheetStatus.textContent=e.message;}finally{sheetBtn.disabled=false;}};
 async function validDeviceMessage(m,type){if(!saneMessage(m,uuid,type)||!m.deviceSigningPublicKeyJwk||m.deviceId!==await keyFingerprint(m.deviceSigningPublicKeyJwk)||m.signingKeyFingerprint!==m.deviceId)return false;return verify(m,m.deviceSigningPublicKeyJwk);}
 async function scan(){const msgs=await history(uuid);locked=msgs.some(m=>m.type==='VOTE');configured=msgs.some(m=>['PUBLIC_KEY','SPREADSHEET','VOTE'].includes(m.type));gen.disabled=locked;return msgs;}
 validateBtn.onclick=async()=>{
  const content=el('div',{},el('p',{text:'Carregando solicitações…'}));
  modal('Validar Pessoas',content,validateBtn);
  try{
   const remote=await remoteConfig(),msgs=remote.msgs,cfg=remote.sheet;
   if(!cfg)throw new Error('Publique a planilha primeiro.');
   const ballot=await fetchSheet(cfg.sheetId,cfg.sheetGid),latest=new Map();
   for(const m of msgs)if(m.type==='NAME_REQUEST'&&await validDeviceMessage(m,'NAME_REQUEST'))latest.set(m.deviceId,m);
   pending=[...latest.values()].filter(m=>!ballot.validated.some(v=>v.deviceId===m.deviceId&&v.name===m.name));
   content.replaceChildren(el('p',{text:'Copie estas linhas para a coluna E e atualize a consulta.'}));
   for(const p of pending){
    const duplicate=[...latest.values()].filter(x=>x.name.toLowerCase()===p.name.toLowerCase()).length>1;
    content.append(el('div',{class:`request ${duplicate?'duplicate':''}`,text:`${p.name}-${p.deviceId}`}));
   }
   if(!pending.length)content.append(el('p',{class:'ok',text:'Não há solicitações pendentes.'}));
   updateBadge();
  }catch(e){content.replaceChildren(el('p',{class:'error',text:e.message}));}
 };
 function updateBadge(){validateBtn.querySelector('.pending')?.remove();if(pending.length)validateBtn.append(el('span',{class:'pending','aria-label':`${pending.length} pendências`,text:pending.length}));}
 async function remoteConfig(){const msgs=await scan(),k=await admin(),good=[];for(const m of msgs)if(['PUBLIC_KEY','SPREADSHEET'].includes(m.type)&&m.adminSigningPublicKeyJwk&&await keyFingerprint(m.adminSigningPublicKeyJwk)===k.fp&&await verify(m,m.adminSigningPublicKeyJwk))good.push(m);return {k,pub:good.filter(x=>x.type==='PUBLIC_KEY').at(-1),sheet:good.filter(x=>x.type==='SPREADSHEET').at(-1),msgs};}
 votePageBtn.onclick=async()=>{const c=el('div',{},el('p',{text:'Verificando o tópico…'}));modal('Página de Votação',c,votePageBtn);try{const {k,pub,sheet}=await remoteConfig();if(!pub||!sheet){c.replaceChildren(el('p',{class:'error'},'É obrigatório publicar a ',el('strong',{text:'Planilha'}),' e a ',el('strong',{text:'Chave Pública'})));return;}try{await fetchSheet(sheet.sheetId,sheet.sheetGid);}catch{c.append(el('p',{class:'error',text:'planilha inválida'}));return;}const url=new URL('../cliente/',location.href);url.search=`?uuid=${uuid}`;url.hash=`k=${k.fp}`;const qrBox=el('div',{class:'qr-code','aria-label':'QR Code para acessar a votação'});c.replaceChildren(qrBox,el('p',{class:'linkline'},el('a',{href:url.href,target:'_blank',rel:'noopener',text:url.href})),el('button',{type:'button','aria-label':'Copiar link',text:'⧉'}));if(window.QRCode)new QRCode(qrBox,{text:url.href,width:260,height:260,correctLevel:QRCode.CorrectLevel.M});else qrBox.textContent='Não foi possível gerar o QR Code.';c.lastChild.onclick=()=>navigator.clipboard.writeText(url.href);}catch(e){c.replaceChildren(el('p',{class:'error',text:e.message}));}};
 panelBtn.onclick=async()=>{try{const k=await admin(),url=new URL('../painel/',location.href);url.search=`?uuid=${uuid}`;url.hash=`k=${k.fp}`;window.open(url.href,'_blank','noopener');}catch(e){alert(e.message);}};
 resultsBtn.onclick=async()=>{const c=el('div',{},el('p',{text:'Decifrando localmente…'}));const dialog=modal('Resultados da Votação',c,resultsBtn);try{const {k,sheet,msgs}=await remoteConfig();if(!sheet)throw new Error('Planilha não publicada.');const ballot=await fetchSheet(sheet.sheetId,sheet.sheetGid),authorized=new Map(ballot.validated.map(v=>[v.deviceId,v])),seen=new Set(),counts=new Map(ballot.questions.map(q=>[q.id,new Map(q.options.map(o=>[o.id,0]))])),rejected={};let accepted=0;for(const m of msgs){if(m.type!=='VOTE'||seen.has(m.deviceId))continue;const auth=authorized.get(m.deviceId);if(!auth){rejected['aparelho não autorizado']=(rejected['aparelho não autorizado']||0)+1;continue;}if(!await validDeviceMessage(m,'VOTE')){rejected['assinatura inválida']=(rejected['assinatura inválida']||0)+1;continue;}seen.add(m.deviceId);try{const p=await decryptVote(m,k.privateKey);if(p.deviceId!==m.deviceId||p.ballotFingerprint!==ballot.ballotFingerprint||p.sheetId!==sheet.sheetId)throw Error();for(const q of ballot.questions){const a=p.answers.find(x=>x.questionId===q.id);if(!a||!Array.isArray(a.optionIds)||a.optionIds.length!==q.count||a.optionIds.some(id=>!counts.get(q.id).has(id)))throw Error();}for(const a of p.answers)for(const id of a.optionIds)counts.get(a.questionId).set(id,counts.get(a.questionId).get(id)+1);accepted++;}catch{rejected['conteúdo cifrado inválido']=(rejected['conteúdo cifrado inválido']||0)+1;}}
 c.replaceChildren(el('p',{class:'ok',text:`${accepted} votos válidos.`}));for(const q of ballot.questions){const box=el('section',{},el('h3',{text:q.text}));for(const o of q.options){const n=counts.get(q.id).get(o.id),den=accepted*q.count;box.append(el('p',{text:`${o.text}: ${n} (${den?((n/den)*100).toFixed(1):'0.0'}%)`}));}c.append(box);}c.append(el('h3',{text:'Rejeições'}));for(const [reason,n]of Object.entries(rejected))c.append(el('p',{text:`${reason}: ${n}`}));const dl=el('button',{type:'button',text:'Baixar relatório'});dl.onclick=()=>downloadReport(c,uuid,ballot.ballotFingerprint,accepted,rejected);c.append(dl);}catch(e){c.replaceChildren(el('p',{class:'error',text:e.message}));}};
 function downloadReport(content,sessionId,fp,total,rejected){const safe=content.cloneNode(true);safe.querySelectorAll('button').forEach(x=>x.remove());const html=`<!doctype html><meta charset="utf-8"><title>Relatório da votação</title><style>body{font:16px system-ui;max-width:800px;margin:40px auto;line-height:1.5}h1{border-bottom:2px solid}</style><h1>Relatório da votação</h1><p>Sessão: ${sessionId}</p><p>Gerado em: ${new Date().toLocaleString('pt-BR')}</p><p>Impressão da cédula: ${fp}</p>${safe.innerHTML}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'text/html'}));a.download=`relatorio-${sessionId}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 async function backupKeys(opener){const p1=el('input',{type:'password'}),p2=el('input',{type:'password'}),go=el('button',{type:'button',text:'Baixar backup'}),out=el('p',{class:'status'});modal('Baixar arquivo de chaves',el('div',{},el('label',{text:'Senha do backup'}),p1,el('label',{text:'Confirmar senha'}),p2,go,out),opener);go.onclick=async()=>{try{if(p1.value.length<8||p1.value!==p2.value)throw Error('Use senhas iguais com ao menos 8 caracteres.');const k=await admin(),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),base=await crypto.subtle.importKey('raw',te.encode(p1.value),'PBKDF2',false,['deriveKey']),aes=await crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations:600000},base,{name:'AES-GCM',length:256},false,['encrypt']),plain=te.encode(JSON.stringify(k)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},aes,plain),file={version:1,uuid,kdf:{name:'PBKDF2',hash:'SHA-256',iterations:600000,salt:b64(salt)},cipher:{name:'AES-GCM',iv:b64(iv)},payload:b64(cipher),fingerprints:{rsa:await sha(depem(k.publicKey,'PUBLIC KEY')),admin:k.fp}};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(file,null,2)],{type:'application/json'}));a.download=`chaves-${uuid}.json`;a.click();p1.value=p2.value='';}catch(e){out.className='status error';out.textContent=e.message;}};}
 function importKeys(opener){const file=el('input',{type:'file',accept:'application/json'}),pass=el('input',{type:'password'}),pub=el('textarea',{placeholder:'Chave pública RSA PEM'}),priv=el('textarea',{placeholder:'Chave privada RSA PEM'}),goFile=el('button',{type:'button',text:'Importar backup'}),goManual=el('button',{type:'button',text:'Importar par RSA'}),out=el('p',{class:'status'});modal('Inserir chaves existentes',el('div',{},el('h3',{text:'Arquivo de backup'}),file,pass,goFile,el('h3',{text:'Importação manual'}),pub,priv,goManual,out),opener);const commit=async k=>{await assertRsaPair(k.publicKey,k.privateKey);await importSigning(k.adminSigningPublicKey,'verify');await importSigning(k.adminSigningPrivateKey,'sign');const probe={value:crypto.randomUUID()};await sign(probe,k.adminSigningPrivateKey);if(!await verify(probe,k.adminSigningPublicKey))throw Error('O par de assinatura administrativa é incompatível.');for(const [n,v]of Object.entries(k))typeof v==='string'?cache.set(n,v):cache.put(n,v);await renderKeys();out.className='status ok';out.textContent='Chaves importadas.';};goFile.onclick=async()=>{try{const f=JSON.parse(await file.files[0].text());if(f.version!==1||f.kdf?.iterations<600000)throw Error('Arquivo inválido.');if(f.uuid!==uuid&&!confirm('Este backup pertence a outro UUID. Importar mesmo assim?'))return;const base=await crypto.subtle.importKey('raw',te.encode(pass.value),'PBKDF2',false,['deriveKey']),aes=await crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt:unb64(f.kdf.salt),iterations:f.kdf.iterations},base,{name:'AES-GCM',length:256},false,['decrypt']),k=JSON.parse(td.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(f.cipher.iv)},aes,unb64(f.payload))));if(await sha(depem(k.publicKey,'PUBLIC KEY'))!==f.fingerprints?.rsa||await keyFingerprint(k.adminSigningPublicKey)!==f.fingerprints?.admin)throw Error('Impressões digitais incompatíveis.');await commit(k);pass.value='';}catch(e){out.className='status error';out.textContent='Não foi possível importar: senha ou arquivo inválido.';}};goManual.onclick=async()=>{try{if(configured)throw Error('Importação manual bloqueada depois de uma publicação.');await assertRsaPair(pub.value,priv.value);const signing=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);await commit({publicKey:pub.value.trim(),privateKey:priv.value.trim(),adminSigningPublicKey:await crypto.subtle.exportKey('jwk',signing.publicKey),adminSigningPrivateKey:await crypto.subtle.exportKey('jwk',signing.privateKey)});}catch(e){out.className='status error';out.textContent=e.message;}};}
 sheetInput.value=cache.get('sheetUrl')||'';await renderKeys();try{await scan();}catch{}
}
